[0m17:27:40.411875 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fad00d8b460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7facfff1cd30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7facfff1ccd0>]}


============================== 17:27:40.417998 | 3b5e4214-e83e-42dc-a053-fd158124c9ff ==============================
[0m17:27:40.417998 [info ] [MainThread]: Running with dbt=1.9.4
[0m17:27:40.419068 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/home/oyetayoadedamola/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run --select merged_data_dynamic', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:27:40.419895 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/oyetayoadedamola/airflow/dags/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:27:40.421695 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.10861337, "process_in_blocks": "0", "process_kernel_time": 0.216821, "process_mem_max_rss": "86464", "process_out_blocks": "8", "process_user_time": 2.174172}
[0m17:27:40.423085 [debug] [MainThread]: Command `dbt run` failed at 17:27:40.422804 after 0.11 seconds
[0m17:27:40.423978 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fad00d8b460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7facfff1c910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7facfff1cc70>]}
[0m17:27:40.424785 [debug] [MainThread]: Flushing usage events
[0m17:27:40.867283 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:32:45.175749 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fea365224f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fea356a4d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fea356a4d60>]}


============================== 15:32:45.181719 | 314016bd-3022-41f8-8000-4f5c36b79783 ==============================
[0m15:32:45.181719 [info ] [MainThread]: Running with dbt=1.9.4
[0m15:32:45.182711 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/home/oyetayoadedamola/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt build --select stg_ghana_customers', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:32:45.183559 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/oyetayoadedamola/airflow/dags/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:32:45.185094 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.09596662, "process_in_blocks": "0", "process_kernel_time": 0.15605, "process_mem_max_rss": "86436", "process_out_blocks": "16", "process_user_time": 2.190905}
[0m15:32:45.186033 [debug] [MainThread]: Command `dbt build` failed at 15:32:45.185847 after 0.10 seconds
[0m15:32:45.186732 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fea365224f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fea356a47f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fea356a4fa0>]}
[0m15:32:45.187297 [debug] [MainThread]: Flushing usage events
[0m15:32:45.355474 [debug] [MainThread]: An error was encountered while trying to flush usage events
